### ISSUE TITLE
reading Generic attributes from a different schema

### ISSUE THREAD

**Issue by calsgeo** [tudelft3d/3DCityDB-QGIS-Loader#3]
Although the plug-in supports multiple 3dCityDB schemas from the same database, the generic attributes are linked and loaded only from the default schema (**citydb**), it should be dynamic.

**Comment by Konstantinos-Pantelios** [comment]
- With this commit ([48d0f3e](https://github.com/tudelft3d/3DCityDB-QGIS-Loader/commit/48d0f3e2920438d4e08844644f30c78328c16318)) in 0.5-dev branch, the relations between the layers and the generic attributes table are set appropriately.
For more details, read the commit's description.

- Additionally, the names of all available auxiliary tables (generics, codelists, enumerations) now have the prefix of their schema.
